# These are supported funding model platforms

github: # [pirunxi]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
#liberapay: lichenghua
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://github.com/e2wugui/zeze/blob/master/doc/sponsor/weixin.jpg','https://github.com/e2wugui/zeze/blob/master/doc/sponsor/zhifubao.jpg']
