package Game;

// auto-generated

public class Schemas extends Zeze.Schemas {
	public Schemas() {
		Zeze.Schemas.Table tempVar = new Zeze.Schemas.Table();
		tempVar.setName("Game_Bag_tbag");
		tempVar.setKeyName("long");
		tempVar.setValueName("Game.Bag.BBag");
		super.AddTable(tempVar);
		Zeze.Schemas.Table tempVar2 = new Zeze.Schemas.Table();
		tempVar2.setName("Game_Buf_tbufs");
		tempVar2.setKeyName("long");
		tempVar2.setValueName("Game.Buf.BBufs");
		super.AddTable(tempVar2);
		Zeze.Schemas.Table tempVar3 = new Zeze.Schemas.Table();
		tempVar3.setName("Game_Equip_tequip");
		tempVar3.setKeyName("long");
		tempVar3.setValueName("Game.Equip.BEquips");
		super.AddTable(tempVar3);
		Zeze.Schemas.Table tempVar4 = new Zeze.Schemas.Table();
		tempVar4.setName("Game_Fight_tfighters");
		tempVar4.setKeyName("Game.Fight.BFighterId");
		tempVar4.setValueName("Game.Fight.BFighter");
		super.AddTable(tempVar4);
		Zeze.Schemas.Table tempVar5 = new Zeze.Schemas.Table();
		tempVar5.setName("Game_Login_taccount");
		tempVar5.setKeyName("string");
		tempVar5.setValueName("Game.Login.BAccount");
		super.AddTable(tempVar5);
		Zeze.Schemas.Table tempVar6 = new Zeze.Schemas.Table();
		tempVar6.setName("Game_Login_tonline");
		tempVar6.setKeyName("long");
		tempVar6.setValueName("Game.Login.BOnline");
		super.AddTable(tempVar6);
		Zeze.Schemas.Table tempVar7 = new Zeze.Schemas.Table();
		tempVar7.setName("Game_Login_trole");
		tempVar7.setKeyName("long");
		tempVar7.setValueName("Game.Login.BRoleData");
		super.AddTable(tempVar7);
		Zeze.Schemas.Table tempVar8 = new Zeze.Schemas.Table();
		tempVar8.setName("Game_Login_trolename");
		tempVar8.setKeyName("string");
		tempVar8.setValueName("Game.Login.BRoleId");
		super.AddTable(tempVar8);
		Zeze.Schemas.Table tempVar9 = new Zeze.Schemas.Table();
		tempVar9.setName("Game_Rank_trank");
		tempVar9.setKeyName("Game.Rank.BConcurrentKey");
		tempVar9.setValueName("Game.Rank.BRankList");
		super.AddTable(tempVar9);
		Zeze.Schemas.Table tempVar10 = new Zeze.Schemas.Table();
		tempVar10.setName("Game_Rank_trankcounters");
		tempVar10.setKeyName("long");
		tempVar10.setValueName("Game.Rank.BRankCounters");
		super.AddTable(tempVar10);
		Zeze.Schemas.Table tempVar11 = new Zeze.Schemas.Table();
		tempVar11.setName("Game_Skill_tskills");
		tempVar11.setKeyName("long");
		tempVar11.setValueName("Game.Skill.BSkills");
		super.AddTable(tempVar11); {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Bag.BBag");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar12 = new Zeze.Schemas.Variable();
			tempVar12.setId(1);
			tempVar12.setName("Money");
			tempVar12.setTypeName("long");
			bean.AddVariable(tempVar12);
			Zeze.Schemas.Variable tempVar13 = new Zeze.Schemas.Variable();
			tempVar13.setId(2);
			tempVar13.setName("Capacity");
			tempVar13.setTypeName("int");
			bean.AddVariable(tempVar13);
			Zeze.Schemas.Variable tempVar14 = new Zeze.Schemas.Variable();
			tempVar14.setId(3);
			tempVar14.setName("Items");
			tempVar14.setTypeName("map");
			tempVar14.setKeyName("int");
			tempVar14.setValueName("Game.Bag.BItem");
			bean.AddVariable(tempVar14);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Bag.BItem");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar15 = new Zeze.Schemas.Variable();
			tempVar15.setId(1);
			tempVar15.setName("Id");
			tempVar15.setTypeName("int");
			bean.AddVariable(tempVar15);
			Zeze.Schemas.Variable tempVar16 = new Zeze.Schemas.Variable();
			tempVar16.setId(2);
			tempVar16.setName("Number");
			tempVar16.setTypeName("int");
			bean.AddVariable(tempVar16);
			Zeze.Schemas.Variable tempVar17 = new Zeze.Schemas.Variable();
			tempVar17.setId(3);
			tempVar17.setName("Extra");
			tempVar17.setTypeName("dynamic");
			bean.AddVariable(tempVar17);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Item.BHorseExtra");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar18 = new Zeze.Schemas.Variable();
			tempVar18.setId(1);
			tempVar18.setName("Speed");
			tempVar18.setTypeName("int");
			bean.AddVariable(tempVar18);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Item.BFoodExtra");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar19 = new Zeze.Schemas.Variable();
			tempVar19.setId(1);
			tempVar19.setName("Ammount");
			tempVar19.setTypeName("int");
			bean.AddVariable(tempVar19);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Equip.BEquipExtra");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar20 = new Zeze.Schemas.Variable();
			tempVar20.setId(1);
			tempVar20.setName("Attack");
			tempVar20.setTypeName("int");
			bean.AddVariable(tempVar20);
			Zeze.Schemas.Variable tempVar21 = new Zeze.Schemas.Variable();
			tempVar21.setId(2);
			tempVar21.setName("Defence");
			tempVar21.setTypeName("int");
			bean.AddVariable(tempVar21);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Buf.BBufs");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar22 = new Zeze.Schemas.Variable();
			tempVar22.setId(1);
			tempVar22.setName("Bufs");
			tempVar22.setTypeName("map");
			tempVar22.setKeyName("int");
			tempVar22.setValueName("Game.Buf.BBuf");
			bean.AddVariable(tempVar22);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Buf.BBuf");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar23 = new Zeze.Schemas.Variable();
			tempVar23.setId(1);
			tempVar23.setName("Id");
			tempVar23.setTypeName("int");
			bean.AddVariable(tempVar23);
			Zeze.Schemas.Variable tempVar24 = new Zeze.Schemas.Variable();
			tempVar24.setId(2);
			tempVar24.setName("AttachTime");
			tempVar24.setTypeName("long");
			bean.AddVariable(tempVar24);
			Zeze.Schemas.Variable tempVar25 = new Zeze.Schemas.Variable();
			tempVar25.setId(3);
			tempVar25.setName("ContinueTime");
			tempVar25.setTypeName("long");
			bean.AddVariable(tempVar25);
			Zeze.Schemas.Variable tempVar26 = new Zeze.Schemas.Variable();
			tempVar26.setId(4);
			tempVar26.setName("Extra");
			tempVar26.setTypeName("dynamic");
			bean.AddVariable(tempVar26);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Buf.BBufExtra");
			bean.setIsBeanKey(false);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Equip.BEquips");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar27 = new Zeze.Schemas.Variable();
			tempVar27.setId(1);
			tempVar27.setName("Items");
			tempVar27.setTypeName("map");
			tempVar27.setKeyName("int");
			tempVar27.setValueName("Game.Bag.BItem");
			bean.AddVariable(tempVar27);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Fight.BFighterId");
			bean.setIsBeanKey(true);
			Zeze.Schemas.Variable tempVar28 = new Zeze.Schemas.Variable();
			tempVar28.setId(1);
			tempVar28.setName("Type");
			tempVar28.setTypeName("int");
			bean.AddVariable(tempVar28);
			Zeze.Schemas.Variable tempVar29 = new Zeze.Schemas.Variable();
			tempVar29.setId(2);
			tempVar29.setName("InstanceId");
			tempVar29.setTypeName("long");
			bean.AddVariable(tempVar29);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Fight.BFighter");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar30 = new Zeze.Schemas.Variable();
			tempVar30.setId(1);
			tempVar30.setName("Attack");
			tempVar30.setTypeName("float");
			bean.AddVariable(tempVar30);
			Zeze.Schemas.Variable tempVar31 = new Zeze.Schemas.Variable();
			tempVar31.setId(2);
			tempVar31.setName("Defence");
			tempVar31.setTypeName("float");
			bean.AddVariable(tempVar31);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Login.BAccount");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar32 = new Zeze.Schemas.Variable();
			tempVar32.setId(1);
			tempVar32.setName("Name");
			tempVar32.setTypeName("string");
			bean.AddVariable(tempVar32);
			Zeze.Schemas.Variable tempVar33 = new Zeze.Schemas.Variable();
			tempVar33.setId(2);
			tempVar33.setName("Roles");
			tempVar33.setTypeName("list");
			tempVar33.setValueName("long");
			bean.AddVariable(tempVar33);
			Zeze.Schemas.Variable tempVar34 = new Zeze.Schemas.Variable();
			tempVar34.setId(3);
			tempVar34.setName("LastLoginRoleId");
			tempVar34.setTypeName("long");
			bean.AddVariable(tempVar34);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Login.BOnline");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar35 = new Zeze.Schemas.Variable();
			tempVar35.setId(1);
			tempVar35.setName("LinkName");
			tempVar35.setTypeName("string");
			bean.AddVariable(tempVar35);
			Zeze.Schemas.Variable tempVar36 = new Zeze.Schemas.Variable();
			tempVar36.setId(2);
			tempVar36.setName("LinkSid");
			tempVar36.setTypeName("long");
			bean.AddVariable(tempVar36);
			Zeze.Schemas.Variable tempVar37 = new Zeze.Schemas.Variable();
			tempVar37.setId(3);
			tempVar37.setName("State");
			tempVar37.setTypeName("int");
			bean.AddVariable(tempVar37);
			Zeze.Schemas.Variable tempVar38 = new Zeze.Schemas.Variable();
			tempVar38.setId(4);
			tempVar38.setName("ReliableNotifyMark");
			tempVar38.setTypeName("set");
			tempVar38.setValueName("string");
			bean.AddVariable(tempVar38);
			Zeze.Schemas.Variable tempVar39 = new Zeze.Schemas.Variable();
			tempVar39.setId(5);
			tempVar39.setName("ReliableNotifyQueue");
			tempVar39.setTypeName("list");
			tempVar39.setValueName("binary");
			bean.AddVariable(tempVar39);
			Zeze.Schemas.Variable tempVar40 = new Zeze.Schemas.Variable();
			tempVar40.setId(6);
			tempVar40.setName("ReliableNotifyConfirmCount");
			tempVar40.setTypeName("long");
			bean.AddVariable(tempVar40);
			Zeze.Schemas.Variable tempVar41 = new Zeze.Schemas.Variable();
			tempVar41.setId(7);
			tempVar41.setName("ReliableNotifyTotalCount");
			tempVar41.setTypeName("long");
			bean.AddVariable(tempVar41);
			Zeze.Schemas.Variable tempVar42 = new Zeze.Schemas.Variable();
			tempVar42.setId(8);
			tempVar42.setName("ProviderId");
			tempVar42.setTypeName("int");
			bean.AddVariable(tempVar42);
			Zeze.Schemas.Variable tempVar43 = new Zeze.Schemas.Variable();
			tempVar43.setId(9);
			tempVar43.setName("ProviderSessionId");
			tempVar43.setTypeName("long");
			bean.AddVariable(tempVar43);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Login.BRoleData");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar44 = new Zeze.Schemas.Variable();
			tempVar44.setId(1);
			tempVar44.setName("Name");
			tempVar44.setTypeName("string");
			bean.AddVariable(tempVar44);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Login.BRoleId");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar45 = new Zeze.Schemas.Variable();
			tempVar45.setId(1);
			tempVar45.setName("Id");
			tempVar45.setTypeName("long");
			bean.AddVariable(tempVar45);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Rank.BConcurrentKey");
			bean.setIsBeanKey(true);
			Zeze.Schemas.Variable tempVar46 = new Zeze.Schemas.Variable();
			tempVar46.setId(1);
			tempVar46.setName("RankType");
			tempVar46.setTypeName("int");
			bean.AddVariable(tempVar46);
			Zeze.Schemas.Variable tempVar47 = new Zeze.Schemas.Variable();
			tempVar47.setId(2);
			tempVar47.setName("ConcurrentId");
			tempVar47.setTypeName("int");
			bean.AddVariable(tempVar47);
			Zeze.Schemas.Variable tempVar48 = new Zeze.Schemas.Variable();
			tempVar48.setId(3);
			tempVar48.setName("TimeType");
			tempVar48.setTypeName("int");
			bean.AddVariable(tempVar48);
			Zeze.Schemas.Variable tempVar49 = new Zeze.Schemas.Variable();
			tempVar49.setId(4);
			tempVar49.setName("Year");
			tempVar49.setTypeName("int");
			bean.AddVariable(tempVar49);
			Zeze.Schemas.Variable tempVar50 = new Zeze.Schemas.Variable();
			tempVar50.setId(5);
			tempVar50.setName("Offset");
			tempVar50.setTypeName("long");
			bean.AddVariable(tempVar50);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Rank.BRankList");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar51 = new Zeze.Schemas.Variable();
			tempVar51.setId(1);
			tempVar51.setName("RankList");
			tempVar51.setTypeName("list");
			tempVar51.setValueName("Game.Rank.BRankValue");
			bean.AddVariable(tempVar51);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Rank.BRankValue");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar52 = new Zeze.Schemas.Variable();
			tempVar52.setId(1);
			tempVar52.setName("RoleId");
			tempVar52.setTypeName("long");
			bean.AddVariable(tempVar52);
			Zeze.Schemas.Variable tempVar53 = new Zeze.Schemas.Variable();
			tempVar53.setId(2);
			tempVar53.setName("Value");
			tempVar53.setTypeName("long");
			bean.AddVariable(tempVar53);
			Zeze.Schemas.Variable tempVar54 = new Zeze.Schemas.Variable();
			tempVar54.setId(3);
			tempVar54.setName("ValueEx");
			tempVar54.setTypeName("binary");
			bean.AddVariable(tempVar54);
			Zeze.Schemas.Variable tempVar55 = new Zeze.Schemas.Variable();
			tempVar55.setId(4);
			tempVar55.setName("AwardTaken");
			tempVar55.setTypeName("bool");
			bean.AddVariable(tempVar55);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Rank.BRankCounters");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar56 = new Zeze.Schemas.Variable();
			tempVar56.setId(1);
			tempVar56.setName("Counters");
			tempVar56.setTypeName("map");
			tempVar56.setKeyName("Game.Rank.BConcurrentKey");
			tempVar56.setValueName("Game.Rank.BRankCounter");
			bean.AddVariable(tempVar56);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Rank.BRankCounter");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar57 = new Zeze.Schemas.Variable();
			tempVar57.setId(1);
			tempVar57.setName("Value");
			tempVar57.setTypeName("long");
			bean.AddVariable(tempVar57);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Skill.BSkills");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar58 = new Zeze.Schemas.Variable();
			tempVar58.setId(1);
			tempVar58.setName("Skills");
			tempVar58.setTypeName("map");
			tempVar58.setKeyName("int");
			tempVar58.setValueName("Game.Skill.BSkill");
			bean.AddVariable(tempVar58);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Skill.BSkill");
			bean.setIsBeanKey(false);
			Zeze.Schemas.Variable tempVar59 = new Zeze.Schemas.Variable();
			tempVar59.setId(1);
			tempVar59.setName("Id");
			tempVar59.setTypeName("int");
			bean.AddVariable(tempVar59);
			Zeze.Schemas.Variable tempVar60 = new Zeze.Schemas.Variable();
			tempVar60.setId(2);
			tempVar60.setName("Extra");
			tempVar60.setTypeName("dynamic");
			bean.AddVariable(tempVar60);
			super.AddBean(bean);
		} {
			var bean = new Zeze.Schemas.Bean();
			bean.setName("Game.Skill.BSkillAttackExtra");
			bean.setIsBeanKey(false);
			super.AddBean(bean);
		}
	}
}
